<!-- CONTENEDORES AJAX --> 
        <div dojoType="dijit.layout.AccordionContainer">          
            <div dojoType="dijit.layout.ContentPane" title="BIENVENIDO" 
                 selected ="true" 
                 align    ="center" 
                 style    ="padding: 40px 40px 40px 40px">
                <?php 
                   echo $this->form;
                ?>		
                <div class="box1" align="center">
						<table width="100%" border="0">
							<tr>
			                <td align="center">
			                	&nbsp;
			                </td>
							</tr>
			                <tr>
			                <td align="center">
			                	<img src="<?php echo $this->baseUrl();?>/imagenes/logo_main.png" height="386px" width="540px"/>
			                </td>
							</tr>
						</table>
					</div>
                </div>            
       </div>