<?php echo $this->doctype(); ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<?php echo $this->headTitle(); ?>
<?php  
$this->dojo()->enable()-> setDjConfigOption('parseOnLoad', true);                        
if($this->dojo()->isEnabled())
{ 
	$this->dojo()
		-> setLocalPath($this->baseUrl().'/js/dojo/dojo/dojo.js')
	    -> addStylesheetModule('dijit.themes.soria');//claro/tundra/nihilo/soria
	echo  $this->dojo();
}
?>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/initRequiredDojo.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jsExpress.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/layoutadm.css"/>
<style type="text/css">@import url(/siswebrceo/public/jscalendar-1.0/calendar-blue.css);</style>
<script type="text/javascript" src="/siswebrceo/public/jscalendar-1.0/calendar.js"></script>
<script type="text/javascript" src="/siswebrceo/public/jscalendar-1.0/lang/calendar-es.js"></script>
<script type="text/javascript" src="/siswebrceo/public/jscalendar-1.0/calendar-setup.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/js/dojo/dojox/grid/resources/Grid.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/js/dojo/dojox/grid/resources/soriaGrid.css" />

<style type="text/css">
    body, html { width:100%; height:100%; margin:0; padding:0; overflow:hidden; }
    #borderContainer { width:100%; height:100% }
</style>
</head>

<body class="soria">

<script type="text/javascript">var MenuLinkedBy="AllWebMenus [4]",awmMenuName="menu",awmBN="850";awmAltUrl="";</script>
<script charset="UTF-8" src="<?php echo $this->baseUrl();?>/menuexp/menu.js" type="text/javascript"></script>
<script type="text/javascript"> 
			var emptyData = { identifier: 'te_id', items: []}; 
			var jsonStore = new dojo.data.ItemFileWriteStore({data: emptyData}); 
			var numItems = 0;
		</script>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 100%">
    <div dojoType="dijit.layout.ContentPane" region="top" align="left" class="ui-widget-header">
	    <?php echo "Usuario actual: ".$this->nameuser;?><div align="right" style="float: right;"><a href="/siswebrceo/public/index/logout">Cerrar sesi&oacute;n</a></div>
    </div>
	
    <div dojoType="dijit.layout.ContentPane" region="leading" style="width: 210px;" align="center">
    	<table border="0" width="100%" height="100%">
    	<tr height="40%"><td><script type="text/javascript">awmBuildMenu();</script></td></tr>
    	<tr><td align="center" valign="bottom">
    	<br>
    		<div id="calendar-container"></div>
    	</td></tr>
    	</table>
    </div>
    
    <div dojoType="dijit.layout.ContentPane" region="center">
        <?php echo $this->layout()->content ?>
    </div>
    
    <div dojoType="dijit.layout.ContentPane" region="bottom" align="center" class="ui-widget-header">
    	<a>Realizado por Gestion Tecnologica El Oro</a>
    </div>
</div>
<script type="text/javascript">
		  function dateChanged(calendar) {
		    if (calendar.dateClicked) {
		      var y = calendar.date.getFullYear();
		      var m = calendar.date.getMonth();
		      var d = calendar.date.getDate();
		      window.location = "#";
		    }
		  };
		  Calendar.setup(
		    {
		      flat         : "calendar-container",
		      flatCallback : dateChanged
		    }
		  );
	</script>
</body>
</html>