        <div dojoType="dijit.layout.AccordionContainer">          
            <div dojoType="dijit.layout.ContentPane" title="INGRESAR LOS DATOS DEL FORMULARIO D-0001" selected="true" align="center">
                <?php 
                   echo $this->form;
                ?>
                <table width="90%" border="0">
                <tr>
                <td>	
                <br>	
	                <fieldset id="el11">
					  <legend style="color:blue;">	DIVISION TERRITORIAL</legend>
						<table border="1" cellspacing="5" width="100%">
							<tr>
						      <td colspan="5">
						      </td>
						    </tr>
						    <tr>
						    <td width="5%"></td>
						    <td width="30%"><label class="estilotxtop"> PROVINCIA : </label></td>
						    <td width="30%"><label class="estilotxtop"> CANTON : </label></td>
						    <td width="30%"><label class="estilotxtop"> PARROQUIA : </label></td>
						    <td width="5%"></td>		                 				   		   
						   </tr>
						   <tr>
						    <td></td>
						   <td>
						   		<select 	id				="provincia"  
				                 			name			="provincia"  
				                 			value			=""
				                 			style			="width:270px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			required		="true"
				                 			invalidMessage	="Elija la decision del usuario"
				                 			onchange         ="mostrardp(this.value)">
				                 			<option value="0"></option>
				                 			<option value="DonacionP">Donacion Parcial</option>
				                 			<option value="Negativa">Negativa a la Donacion</option>
						     				<option value="Revocatoria">Revocatoria de la voluntad</option>
						     				<option value="RevocatoriaP">Revocatoria de la voluntad Parcial</option>
				                 </select>
				           </td>
						   <td>
						   		<select 	id				="canton"  
				                 			name			="canton"  
				                 			value			=""
				                 			style			="width:270px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			required		="true"
				                 			invalidMessage	="Elija la decision del usuario"
				                 			onchange         ="mostrardp(this.value)">
				                 			<option value="0"></option>
				                 			<option value="DonacionP">Donacion Parcial</option>
				                 			<option value="Negativa">Negativa a la Donacion</option>
						     				<option value="Revocatoria">Revocatoria de la voluntad</option>
						     				<option value="RevocatoriaP">Revocatoria de la voluntad Parcial</option>
				                 </select>
				           </td>
						   <td >
						   		<select 	id				="parroquia"  
				                 			name			="parroquia"  
				                 			value			=""
				                 			style			="width:270px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			required		="true"
				                 			invalidMessage	="Elija la decision del usuario"
				                 			onchange         ="mostrardp(this.value)">
				                 			<option value="0"></option>
				                 			<option value="DonacionP">Donacion Parcial</option>
				                 			<option value="Negativa">Negativa a la Donacion</option>
						     				<option value="Revocatoria">Revocatoria de la voluntad</option>
						     				<option value="RevocatoriaP">Revocatoria de la voluntad Parcial</option>
				                 </select>
				           </td>
						   <td ></td>		                 				   		   
						   </tr>
							<tr>
						    <td></td>
						    <td colspan="3">
						    <input 
						                 		id				="lugfec"
						                 		name			="lugfec" 
						                 		type			="text"
						                 		value			="" 
						                 		style			="width:400px;font:xx-large;" 
						                 		dojotype		="dijit.form.ValidationTextBox"/>
						    </td>
						    <td ></td>		                 				   		   
						   </tr>
						   
						</table>
	               </fieldset>
	               <br>
				  
				  <table border="0" cellspacing="0" cellpadding="0" width="100%">
	               <tr>
						<td colspan="2"></td>
				   </tr>
				   <tr>
						<td><div align="center">
						<button class="estilotxtop" dojoType="dijit.form.Button" onclick="verformulariod1();"><img src="<?php echo $this->baseUrl();?>/imagenes/save.png" height="20px" width="20px"/>
						Ver Formulario
						</button>
						</div>
						</td>
						<td><div align="left">
							<button class="estilotxtop" dojoType="dijit.form.Button" onclick="cancelarformd1();"><img src="<?php echo $this->baseUrl();?>/imagenes/cancel.png" height="24px" width="24px"/> Cancelar</button>
						</div>
						</td>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
				   </tr>
				   </table>
               </td>
               </tr>
               </table>
            </div>            
       </div>                                