        <div dojoType="dijit.layout.AccordionContainer">          
            <div dojoType="dijit.layout.ContentPane" title="INGRESAR LOS DATOS DEL FORMULARIO D-0001" selected="true" align="center">
                <?php 
                   echo $this->form;
                ?>
                <table width="90%" border="0">
                <tr>
                <td>	
                <br>	
	                <fieldset id="el11">
					  <legend style="color:blue;">	Informacion del Usuario</legend>
						<table border="0" cellspacing="5" width="100%">
							<tr>
						      <td colspan="2">
							      	<div id="aviso" style="display: none;" align="center"><font color="red">Los campos marcados(*) son obligatorios</font></div>
						      </td>
						    </tr>
						    <tr>
						   <td width="35%"><label class="estilotxtop"> Lugar y Fecha : </label></td>
						   <td ><input 
						                 		id				="lugfec"
						                 		name			="lugfec" 
						                 		type			="text"
						                 		maxlength     	="200"  
						                 		value			="" 
						                 		style			="width:270px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox"
						                 		onfocus         ="getFecha();"/>
						   </td>		                 				   		   
						   </tr>
							<tr>
						   <td width="35%"><label class="estilotxtop"> Cedula : </label></td>
						   <td ><input 
						                 		id				="cedula"
						                 		name			="cedula" 
						                 		type			="text"
						                 		maxlength     	="13"  
						                 		value			="" 
						                 		style			="width:150px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		uppercase       ="true"/>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><label class="estilotxtop"> Apellidos y nombres: </label></td>
						   <td ><input 
						                 		id				="apellidosop"
						                 		name			="apellidosop" 
						                 		type			="text"
						                 		value			=""
						                 		maxlength     	="100"
						                 		uppercase		="true"
						                 		style			="width:400px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		invalidmessage	="Ingrese los apellidos y nombres del usuario"/>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><label class="estilotxtop"> Decision del usuario: </label></td>
						   <td ><select 	id				="decision"  
				                 			name			="decision"  
				                 			value			=""
				                 			style			="width:270px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			required		="true"
				                 			invalidMessage	="Elija la decision del usuario"
				                 			onchange         ="mostrardp(this.value)">
				                 			<option value="0"></option>
				                 			<option value="DonacionP">Donacion Parcial</option>
				                 			<option value="Negativa">Negativa a la Donacion</option>
						     				<option value="Revocatoria">Revocatoria de la voluntad</option>
						     				<option value="RevocatoriaP">Revocatoria de la voluntad Parcial</option>
				                 </select>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><div id="lbldp" style="display: none;"><label class="estilotxtop"></label></div></td>
						   <td ><div id="txtdp" style="display: none;">
						        <input type="radio" name="dparcial" id="organos" value="organos" /><label for="organos" class="estilotxtop">Organos</label>
							    <br />
							    <input type="radio" name="dparcial" id="tejidos" value="tejidos" /><label for="tejidos" class="estilotxtop">Tejidos</label>
							    </div>
						   </td>		                 				   		   
						   </tr>
						</table>
	               </fieldset>
	               <br>
				  
				  <table border="0" cellspacing="0" cellpadding="0" width="100%">
	               <tr>
						<td colspan="2"></td>
				   </tr>
				   <tr>
						<td><div align="center">
						<button class="estilotxtop" dojoType="dijit.form.Button" onclick="verformulariod1();"><img src="<?php echo $this->baseUrl();?>/imagenes/save.png" height="20px" width="20px"/>
						Ver Formulario
						</button>
						</div>
						</td>
						<td><div align="left">
							<button class="estilotxtop" dojoType="dijit.form.Button" onclick="cancelarformd1();"><img src="<?php echo $this->baseUrl();?>/imagenes/cancel.png" height="24px" width="24px"/> Cancelar</button>
						</div>
						</td>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
				   </tr>
				   </table>
               </td>
               </tr>
               </table>
            </div>            
       </div>                                