<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jsControlSesion.js"></script>
<div id="content">
		<table id="tablalogin"  cellspacing="0" align="left" border="0" cellpadding="0">
        				<tr id="taglogin">
           					<td id="Login-label">
               					<label for  ="lblLogin" 
                      				   class="required" 
                      				   style="float:left;font-family:sans-serif;font-size:small;">
                      	        <b style="font:bold 14px verdana,arial,sans-serif;color:#5B595B;">Usuario</b>
               					</label>
          					</td> 
           					<td> 
                 				<input promptMessage = "Ingrese el Usuario "
                        				id            = "login"
                        				name          = "login" 
                        				type          = "text"  
                        				maxlength     = "25"   
                        				value         = "" 
                        				style         = "width:200px;height:20px;font-family:sans-serif;font-size:small;border: solid 1px #636163;" 
                        				dojoType      = "dijit.form.ValidationTextBox" 
                       					required      = "true" 
                        				invalidMessage= "Ingrese su usuario"
                        				lowercase     = "true" 
                         		/>                      
           					</td>
           					<td>
           						<img  src="<?php echo $this->baseUrl();?>/imagenes/usu.png"  style="width:30px;height:30px;margin-left:2px;" />
           					</td>          					
         				</tr>                    
       					<tr id="tagClave" style="margin-top:-10px;">
           					<td id="Clave-label">
               					<label for  ="lblClave" 
                      					class="required" >
                      			<b style="font:bold 14px verdana,arial,sans-serif;color:#5B595B;">Clave</b>
               					</label>
           					</td> 
           				<td> 
                 			<input 
                        			id            = "clave"
                        			name          = "clave" 
                        			type          = "password"  
                        			maxlength     = "10"   
                        			value         = "" 
                        			style			="width:120px;font:12px;float: left;border: solid 1px #636163;" 
                        			onkeypress      ="entrarsistema(event)"/>                      
           				</td>
           				<td>
           					<img  src="<?php echo $this->baseUrl();?>/imagenes/key.png"  style="width:30px;height:30px;margin-left:2px;" />
           				</td>
         			</tr> 
         			<tr> 
         				<td colspan="3">         
         				<div  align="center"> 
              				<button 
              					id="btnok"  	
              					dojoType="dijit.form.Button" 
              					onclick = "autenticarUsuario()"
								title = "Iniciar Sesión">Ingresar</button>
						</div>
          				</td>    
        			</tr> 
        			<tr>
	           			<td colspan="3">
	           			&nbsp;                      
	           			</td>
	         		</tr>
     			</table>
</div>