        <div dojoType="dijit.layout.AccordionContainer">          
            <div dojoType="dijit.layout.ContentPane" title="CONSULTAR OPERADOR" selected="true">
                <?php 
                   echo $this->form;
                ?>	
                <div class="box" id="wipeDisplayNode">	
                <br>	
					<table border="0" cellspacing="5" width="100%">
					<tr>	
					   <td width="20%"><label class="estilotxtop"> Buscar por : </label></td>
					   <td width="20%">
					   			<select 	id				="buscarpor"  
				                 			name			="buscarpor"  
				                 			value			=""
				                 			style			="width:150px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			invalidMessage	="Elija el criterio de busqueda"
				                 			onchange        ="mostrarciudad(this.value)">
				                 			<option value="0"></option>
				                 			<option value="Por ciudad">Ciudad o lugar</option>
				                 			<option value="Todos">Todos</option>
				                 </select></td>
					   <td width="20%"></td>
					   <td width="20%"></td>
					   <td width="20%"></td>
					</tr>
					<tr>	
					   <td width="20%"><div id="lblciudad" style="display: none;"><label class="estilotxtop"> Ciudad o lugar donde Opera </label></div></td>
					   <td width="20%"><div id="txtciudad" style="display: none;">
					   			<select 	id				="ciudad"  
				                 			name			="ciudad"  
				                 			value			=""
				                 			style			="width:150px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			invalidMessage	="Elija la ciudad donde Opera">
				                 			<option value="0"></option>
				                 			<option value="Brigada">Brigada</option>
				                 			<option value="El Guabo">El Guabo</option>
						     				<option value="Huaquillas">Huaquillas</option>
						     				<option value="Machala">Machala</option>
						     				<option value="Pasaje">Pasaje</option>
						     				<option value="Pinas">Pi&ntilde;as</option>
						     				<option value="Santa Rosa">Santa Rosa</option>
				                 </select>
				                 </div>
				       </td>
					   <td width="20%"></td>
					   <td width="20%"></td>
					   <td width="20%"></td>
					</tr>
					   	<tr>
							<td colspan="2"></td>
							<td>
								<div align="center">
									<button class="estilotxtop" dojoType="dijit.form.Button" onclick="buscarOperadores();"><img src="<?php echo $this->baseUrl();?>/imagenes/search_icon.png" height="28px" width="28px"/>Buscar</button>
				                 </div>
							</td>
							<td colspan="2">
							<div id="idEspera" style="display: none;" align="left">
			                 		<img  src="<?php echo $this->baseUrl();?>/imagenes/espera.gif" height="32px" width="32px"/>
			                 	</div>
							</td>
						</tr>				  					   					   
						<tr>
							<td colspan="5">			
					          <table dojotype="dojox.grid.DataGrid" id="grilla" jsId="grilla" height="200px" style="font-family:'Trebuchet MS', Helvetica, sans-serif;font-size:12px;border: 1px solid #9AC4D8;">
					            <thead>
					              <tr>
					                <th width="25px" formatter="checkFormatter">Nro</th>
					                <th field="op_id" width="5%" hidden="true">Id</th>
					                <th field="op_cedula" width="80px">Cedula</th>
					                <th field="nombreape" width="250px">Nombres y Apellidos</th>
					                <th field="op_ciudad" width="100px">Ciudad donde Opera</th>	
					                <th field="op_estado" width="50px">Estado</th>
					              </tr>
					            </thead>
					        </table>
							</td>
						</tr>
						<tr><td colspan="5"><div style="font-family:'Trebuchet MS', Helvetica, sans-serif;font-size:11px;font: bold; color: #9AC4D8;">Nota: Para modificar o eliminar un operador debe seleccionar la fila.</div></td></tr>
						<tr>
							<td colspan="2">
							<div align="center">
								<button class="estilotxtop" dojoType="dijit.form.Button" onclick="eliminarOperador();"><img  src="<?php echo $this->baseUrl();?>/imagenes/socio_delete.png" height="32px" width="32px"/> Eliminar Operador</button>
							</div>
							</td>
							<td colspan="1">
							</td>
							<td colspan="2">
							<div align="center">
								<button class="estilotxtop" dojoType="dijit.form.Button" onclick="buscarmodificaroperador();"><img  src="<?php echo $this->baseUrl();?>/imagenes/socio_delete.png" height="32px" width="32px"/> Modificar Operador</button>
							</div>
							</td>
						</tr>
					</table>					
            	</div>
            <div id="mostraroperador" style="display: none;" align="center">
            <div  class="box">
            <br>
			<table width="90%">
                <tr>
                <td>
             		<fieldset id="el11">
					  <legend style="color:blue;">	Datos del Operador</legend>
						<table border="0" cellspacing="5" width="100%">
							<tr>
						      <td colspan="2">
							      	<div id="aviso" style="display: none;" align="center"><font color="red">Los campos marcados(*) son obligatorios</font></div>
						      </td>
						    </tr>
						    <tr>
						   <td ><div id="lblid" style="display: none;"> Id : </div></td>
						   <td ><div id="txtid" style="display: none;">
						   		<input 
						                 		id				="idop"
						                 		name			="idop" 
						                 		type			="text"
						                 		value			="" 
						                 		style			="width:100px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		disabled        ="disabled"/></div>
						   </td>		                 				   		   
						   </tr>
							<tr>
						   <td width="35%"><label class="estilotxtop"> Cedula : </label></td>
						   <td ><input 
						                 		id				="cedula"
						                 		name			="cedula" 
						                 		type			="text"
						                 		maxlength     	="10"  
						                 		value			="" 
						                 		style			="width:150px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		uppercase       ="true"
						                 		invalidmessage	="Ing. el numero de cedula del operador"/>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><label class="estilotxtop"> Apellidos : </label></td>
						   <td ><input 
						                 		id				="apellidosop"
						                 		name			="apellidosop" 
						                 		type			="text"
						                 		value			=""
						                 		maxlength     	="100"
						                 		uppercase		="true"
						                 		style			="width:300px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		invalidmessage	="Ingrese los apellidos del Operador"/>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><label class="estilotxtop"> Nombres : </label></td>
						   <td ><input 
						                 		id				="nombresop"
						                 		name			="nombresop" 
						                 		type			="text"
						                 		value			=""
						                 		maxlength     	="100"
						                 		uppercase		="true"
						                 		style			="width:300px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		invalidmessage	="Ingrese los Nombres del Operador"/>
						   </td>		                 				   		   
						   </tr>
						   
						   <tr>
						   <td ><label class="estilotxtop"> Ciudad o lugar donde Opera: </label></td>
						   <td ><select 	id				="ciudad1"  
				                 			name			="ciudad1"  
				                 			value			=""
				                 			style			="width:150px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			required		="true"
				                 			invalidMessage	="Elija la ciudad donde Opera">
				                 			<option value="0"></option>
				                 			<option value="Brigada">Brigada</option>
				                 			<option value="El Guabo">El Guabo</option>
						     				<option value="Huaquillas">Huaquillas</option>
						     				<option value="Machala">Machala</option>
						     				<option value="Pasaje">Pasaje</option>
						     				<option value="Pinas">Pi&ntilde;as</option>
						     				<option value="Santa Rosa">Santa Rosa</option>
				                 </select>
						   </td>		                 				   		   
						   </tr>
						</table>
	               </fieldset>
					   
				   <table border="0" cellspacing="5" width="80%">
					   <tr>
							<td colspan="2">&nbsp;</td>
						</tr>
						<tr>
							<td><div align="center">
								<button class="estilotxtop" dojoType="dijit.form.Button" onclick="actualizarOperador();"><img src="<?php echo $this->baseUrl();?>/imagenes/save.png" height="20px" width="20px"/> Actualizar Operador</button>
							</div>
							</td>
							<td><div align="center">
								<button class="estilotxtop" dojoType="dijit.form.Button" onclick="cancelarActOperador();"><img src="<?php echo $this->baseUrl();?>/imagenes/cancel.png" height="24px" width="24px"/> Cancelar</button>
							</div>
							</td>
						</tr>																				
				     </table>
					</td>
					</tr>
					</table>
					</div>
					</div>
            </div>            
       </div>                                