        <div dojoType="dijit.layout.AccordionContainer">          
            <div dojoType="dijit.layout.ContentPane" title="INGRESAR OPERADOR" selected="true" align="center">
                <?php 
                   echo $this->form;
                ?>
                <table width="90%" border="0">
                <tr>
                <td>	
                <br>	
	                <fieldset id="el11">
					  <legend style="color:blue;">	Datos del Operador</legend>
						<table border="0" cellspacing="5" width="100%">
							<tr>
						      <td colspan="2">
							      	<div id="aviso" style="display: none;" align="center"><font color="red">Los campos marcados(*) son obligatorios</font></div>
						      </td>
						    </tr>
							<tr>
						   <td width="35%"><label class="estilotxtop"> Cedula : </label></td>
						   <td ><input 
						                 		id				="cedula"
						                 		name			="cedula" 
						                 		type			="text"
						                 		maxlength     	="10"  
						                 		value			="" 
						                 		style			="width:150px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		uppercase       ="true"
						                 		invalidmessage	="Ing. el numero de cedula del operador"/>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><label class="estilotxtop"> Apellidos : </label></td>
						   <td ><input 
						                 		id				="apellidosop"
						                 		name			="apellidosop" 
						                 		type			="text"
						                 		value			=""
						                 		maxlength     	="100"
						                 		uppercase		="true"
						                 		style			="width:300px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		invalidmessage	="Ingrese los apellidos del Operador"/>
						   </td>		                 				   		   
						   </tr>
						   <tr>
						   <td ><label class="estilotxtop"> Nombres : </label></td>
						   <td ><input 
						                 		id				="nombresop"
						                 		name			="nombresop" 
						                 		type			="text"
						                 		value			=""
						                 		maxlength     	="100"
						                 		uppercase		="true"
						                 		style			="width:300px;font:12px;float: left;" 
						                 		dojotype		="dijit.form.ValidationTextBox" 
						                 		invalidmessage	="Ingrese los Nombres del Operador"/>
						   </td>		                 				   		   
						   </tr>
						   
						   <tr>
						   <td ><label class="estilotxtop"> Ciudad o lugar donde Opera: </label></td>
						   <td ><select 	id				="ciudad"  
				                 			name			="ciudad"  
				                 			value			=""
				                 			style			="width:150px;font:12px;float: left;" 
				                 			dojoType		="dijit.form.FilteringSelect" 
				                 			autoComplete	="true"  
				                 			required		="true"
				                 			invalidMessage	="Elija la ciudad donde Opera">
				                 			<option value="0"></option>
				                 			<option value="Brigada">Brigada</option>
				                 			<option value="El Guabo">El Guabo</option>
						     				<option value="Huaquillas">Huaquillas</option>
						     				<option value="Machala">Machala</option>
						     				<option value="Pasaje">Pasaje</option>
						     				<option value="Pi&ntilde;as">Pi&ntilde;as</option>
						     				<option value="Santa Rosa">Santa Rosa</option>
				                 </select>
						   </td>		                 				   		   
						   </tr>
						</table>
	               </fieldset>
	               <br>
				  
				  <table border="0" cellspacing="0" cellpadding="0" width="100%">
	               <tr>
						<td colspan="2"></td>
				   </tr>
				   <tr>
						<td><div align="center">
						<button class="estilotxtop" dojoType="dijit.form.Button" onclick="guardarOperador();"><img src="<?php echo $this->baseUrl();?>/imagenes/save.png" height="20px" width="20px"/>
						Guardar Operador
						</button>
						</div>
						</td>
						<td><div align="left">
							<button class="estilotxtop" dojoType="dijit.form.Button" onclick="cancelarOperadoring();"><img src="<?php echo $this->baseUrl();?>/imagenes/cancel.png" height="24px" width="24px"/> Cancelar</button>
						</div>
						</td>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
				   </tr>
				   </table>
               </td>
               </tr>
               </table>
            </div>            
       </div>                                